// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfdxekfkfylqcpzljxcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZHhla2ZrZnlscWNwemxqeGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MTIzMjAsImV4cCI6MjA1MjM4ODMyMH0.nI9Ors1LzMaFXJQMx3-dmw5vSCYZPo_4nq_RHt8rbPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);